spring.application.name=hrms
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/hrms
spring.datasource.username=adi
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=never
