CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    username VARCHAR(80) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(254) NOT NULL,
    monthly_salary DECIMAL(12, 2) NOT NULL,
    onboarding_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    bank_name VARCHAR(120),
    bank_account_number VARCHAR(80),
    bank_ifsc VARCHAR(20),
    shift_type VARCHAR(20) NOT NULL DEFAULT 'OFFICE',
    custom_shift_start_time TIME,
    custom_shift_end_time TIME,
    CONSTRAINT uk_employee_email UNIQUE (email),
    CONSTRAINT uk_employee_username UNIQUE (username)
);

CREATE TABLE employee_documents (
    employee_id BIGINT NOT NULL,
    document_reference VARCHAR(1000) NOT NULL,
    CONSTRAINT fk_document_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE attendance_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    punch_in TIMESTAMP(6) NOT NULL,
    punch_out TIMESTAMP(6),
    status VARCHAR(20) NOT NULL DEFAULT 'PRESENT',
    CONSTRAINT fk_attendance_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE INDEX ix_attendance_employee_start
    ON attendance_sessions (employee_id, punch_in);

CREATE TABLE payroll_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    salary_month INT NOT NULL,
    salary_year INT NOT NULL,
    total_working_days INT NOT NULL,
    full_pay_days INT NOT NULL,
    half_pay_days INT NOT NULL,
    unpaid_days INT NOT NULL,
    overtime_achievement_days INT NOT NULL,
    overtime_hours DECIMAL(8, 2) NOT NULL,
    monthly_salary DECIMAL(12, 2) NOT NULL,
    payable_salary DECIMAL(12, 2) NOT NULL,
    calculated_at TIMESTAMP(6) NOT NULL,
    payment_request_created BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_payroll_employee_period UNIQUE (employee_id, salary_year, salary_month),
    CONSTRAINT fk_payroll_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE salary_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id BIGINT NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    bank_name VARCHAR(120) NOT NULL,
    masked_account VARCHAR(80) NOT NULL,
    bank_ifsc VARCHAR(20) NOT NULL,
    transaction_reference VARCHAR(120),
    created_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6),
    CONSTRAINT uk_payment_payroll UNIQUE (payroll_id),
    CONSTRAINT fk_payment_payroll FOREIGN KEY (payroll_id) REFERENCES payroll_records (id)
);
